# Site settings
title: 读客
header-img: img/home-bg.jpg
email: byronwind@gmail.com
description: "路在远方"
baseurl: ""
url: "http://github.dudukr.com"
twitter_username: LiGQLi
github_username:  byronwind
facebook_username:  liguoqing

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : dudukr


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "byronwind"
      header-img: "img/post-bg.jpg" # We don't want posts without a header image, that whould mean white on white
