# Site settings
title: DuduLili
header-img: img/home-bg.jpg
email: byronwind@gmail.com
description: "路在远方"
baseurl: ""
url: "http://github.dudukr.com"
twitter_username: LiGQLi
github_username:  byronwind
facebook_username:  liguoqing

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
